sudo: false
matrix:
  fast_finish: true
  include:
  - python: '3.4'
    env: TOXENV=py34
  - python: '3.5'
    env: TOXENV=py35
  - python: '3.6'
    env: TOXENV=py36
  - python: '3.7'
    env: TOXENV=py37
    dist: xenial
    sudo: true
  - python: '3.5'
    env: TOXENV=desc
language: python
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  user: colinodell-auto
  password:
    secure: e+g/dR40qDv8uKtFTy6PdbaBdJA6/0WTAper32B6DwYkXg2f2b+bU8bf0TkbfZ5NFfN7YC+YJcTOiqRfrSlxRHt2X3mjS5fvBEQXMFmW8swCnSCKM+CdpgF7ydLRdo8iDN5QDBicqiE7ps/3ZXPBEYuaLqxYhJ29/a+ZK64KHKOC+duOaCh4tQue22+kaFhw1j1sx59qB9DFYvrtCRuPBPC/510f9By0bU17VPEP/wUZJTn/kmSDVUob9B3IPfW1TDtew1j1vM2T5CQ0mZxb/lHU5892P/rrbnoxnaHvKYvlxVqsaDOo2tnZhJY7FLHoqObBHatsWs0wMtxs+rOVxtO97r5oeGp1wWgXGE/KIRjyQUoW9oxRYnvNQoRIKw5w/SRtRfKheXO4Uucd/52Xc+kbe3cMZrYzhr5kErxBGkcFUjpoWP6YbJ6O9EoGQjH25+DNVLCubectdQSuzYLHqvGr7y1UYlbsjBXqQYzA51e8BlJPIMfI0xzR2TlyZNSn7PZvb4nBpmlHMobvO6Ry14NKPnxDKCwncrKneOZ4iprCgZiR4qWSYwR8SZahhDi8k7pLtxmq9qzuLcFbTuhhIGB/gomFl0B1gaUgE6u69o6UB2YYOGQpdGJO99v8BtaJ0VTLIyOtGSSh6KwvOufHh3cutGq2Yi6t8OXu4Vf6gtw=
  on:
    tags: true
    python: 3.6
    condition: "$TOXENV != desc"
  distributions: sdist
